[theme]
primaryColor = "#F39C12"
backgroundColor = "#2C3E50"
secondaryBackgroundColor = "#34495E"
textColor = "#ECF0F1"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
maxUploadSize = 1024